/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciadeviaje;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author LuisMiguel
 */
public class VentanaInicial extends javax.swing.JFrame {

    private final Logger log;
    private AerolineaOBus bus;
    private ArrayList<AerolineaOBus> buses;
    private HotelOResort hotel;
    private ArrayList<HotelOResort> hoteles;
    private Crucero crucero;
    private ArrayList<Crucero> cruceros;
    private EntidadFinanciera financiera;
    private ArrayList<EntidadFinanciera> financieras;
    private Cliente cliente;
    private ArrayList<Cliente> clientes;
    private Turistico turistico;
    private ArrayList<Turistico> turisticos;
    private Entretenimiento entretenimiento;
    private ArrayList<Entretenimiento> entretenimientos;
    private Paquete paquete;
    private ArrayList<Paquete> paquetes;
    private Reservacion reservacion;
    private ArrayList<ArrayList> reservaciones;
    private RentaAuto auto;
    private ArrayList<RentaAuto> autos;
    private Asiento asiento;
    private ArrayList<Asiento> asientos;
    private Habitacion habitacion;
    private ArrayList<Habitacion> habitaciones;
    private Camarote camarote;
    private ArrayList<Camarote> camarotes;
    
    public VentanaInicial() {
        this.log = LogManager.getLogger(VentanaInicial.class);
        initComponents();
        initRadioButtons();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setTitle("Clientes");
        
        buses = new ArrayList<>();
        hoteles = new ArrayList<>();
        cruceros = new ArrayList<>();
        financieras = new ArrayList<>();
        clientes = new ArrayList<>();
        turisticos = new ArrayList<>();
        entretenimientos = new ArrayList<>();
        paquetes = new ArrayList<>();
        reservaciones = new ArrayList<>();
        autos = new ArrayList<>();    
        asientos = new ArrayList<>();
        habitaciones = new ArrayList<>();
        camarotes = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jMenuItem10 = new javax.swing.JMenuItem();
        panelprincipal = new javax.swing.JPanel();
        panelinferior = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelsuperior = new javax.swing.JPanel();
        panelbuscar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buscartext = new javax.swing.JTextField();
        buscarbutton = new javax.swing.JButton();
        paneletiquetas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        paneldatos = new javax.swing.JPanel();
        nombretext = new javax.swing.JTextField();
        apellidotext = new javax.swing.JTextField();
        tarjetatext = new javax.swing.JTextField();
        nacimientotext = new javax.swing.JTextField();
        telefonotext = new javax.swing.JTextField();
        moviltext = new javax.swing.JTextField();
        panelradiobuttons = new javax.swing.JPanel();
        anualbutton = new javax.swing.JRadioButton();
        mensualbutton = new javax.swing.JRadioButton();
        regularbutton = new javax.swing.JRadioButton();
        frecuentebutton = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        basicobutton = new javax.swing.JRadioButton();
        premiumbutton = new javax.swing.JRadioButton();
        platinobutton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        etiquetaspaquetepanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        paquetepanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        busradiobutton = new javax.swing.JRadioButton();
        cruceroradiobutton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        economicoradiobutton = new javax.swing.JRadioButton();
        lujoradiobutton = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 475));

        panelprincipal.setLayout(new java.awt.BorderLayout());

        panelinferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jButton1.setText("Guardar");
        panelinferior.add(jButton1);

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelinferior.add(jButton2);

        jButton3.setText("Eliminar");
        panelinferior.add(jButton3);

        panelprincipal.add(panelinferior, java.awt.BorderLayout.PAGE_END);

        panelbuscar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Buscar cliiente (Id)");
        panelbuscar.add(jLabel2);

        buscartext.setColumns(25);
        panelbuscar.add(buscartext);

        buscarbutton.setText("Buscar");
        buscarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbuttonActionPerformed(evt);
            }
        });
        panelbuscar.add(buscarbutton);

        paneletiquetas.setLayout(new java.awt.GridLayout(8, 0));

        jLabel1.setText("Nombres");
        paneletiquetas.add(jLabel1);

        jLabel3.setText("Apellidos");
        paneletiquetas.add(jLabel3);

        jLabel4.setText("Número de tarjeta");
        paneletiquetas.add(jLabel4);

        jLabel5.setText("Fecha nacimiento");
        paneletiquetas.add(jLabel5);

        jLabel6.setText("Teléfono");
        paneletiquetas.add(jLabel6);

        jLabel7.setText("Móvil");
        paneletiquetas.add(jLabel7);

        jLabel8.setText("Frecuencia");
        paneletiquetas.add(jLabel8);

        jLabel9.setText("Clasificación monto");
        paneletiquetas.add(jLabel9);

        paneldatos.setLayout(new java.awt.GridLayout(8, 0, 0, 12));

        nombretext.setColumns(25);
        paneldatos.add(nombretext);

        apellidotext.setColumns(25);
        paneldatos.add(apellidotext);

        tarjetatext.setColumns(25);
        paneldatos.add(tarjetatext);

        nacimientotext.setColumns(25);
        paneldatos.add(nacimientotext);

        telefonotext.setColumns(25);
        paneldatos.add(telefonotext);

        moviltext.setColumns(25);
        paneldatos.add(moviltext);

        anualbutton.setSelected(true);
        anualbutton.setText("Anual");
        anualbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anualbuttonActionPerformed(evt);
            }
        });
        panelradiobuttons.add(anualbutton);

        mensualbutton.setText("Mensual");
        panelradiobuttons.add(mensualbutton);

        regularbutton.setText("Regular");
        panelradiobuttons.add(regularbutton);

        frecuentebutton.setText("Frecuente");
        panelradiobuttons.add(frecuentebutton);

        paneldatos.add(panelradiobuttons);

        basicobutton.setText("Básico");
        jPanel4.add(basicobutton);

        premiumbutton.setText("Premium");
        jPanel4.add(premiumbutton);

        platinobutton.setText("Platino");
        jPanel4.add(platinobutton);

        paneldatos.add(jPanel4);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        etiquetaspaquetepanel.setLayout(new java.awt.GridLayout(4, 0));

        jLabel10.setText("Paquete:");
        etiquetaspaquetepanel.add(jLabel10);

        jLabel11.setText("Monto");
        etiquetaspaquetepanel.add(jLabel11);

        jLabel12.setText("Transporte");
        etiquetaspaquetepanel.add(jLabel12);

        jLabel13.setText("Clase");
        etiquetaspaquetepanel.add(jLabel13);

        paquetepanel.setLayout(new java.awt.GridLayout(4, 0));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Familiar", "Negocios", "Express" }));
        paquetepanel.add(jComboBox1);
        paquetepanel.add(jTextField1);

        busradiobutton.setText("Bus/Avion");
        jPanel5.add(busradiobutton);

        cruceroradiobutton.setText("Crucero");
        jPanel5.add(cruceroradiobutton);

        paquetepanel.add(jPanel5);

        economicoradiobutton.setText("Económico");
        jPanel2.add(economicoradiobutton);

        lujoradiobutton.setText("De lujo");
        lujoradiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lujoradiobuttonActionPerformed(evt);
            }
        });
        jPanel2.add(lujoradiobutton);

        paquetepanel.add(jPanel2);

        javax.swing.GroupLayout panelsuperiorLayout = new javax.swing.GroupLayout(panelsuperior);
        panelsuperior.setLayout(panelsuperiorLayout);
        panelsuperiorLayout.setHorizontalGroup(
            panelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelsuperiorLayout.createSequentialGroup()
                        .addComponent(paneletiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paneldatos, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaspaquetepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paquetepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelsuperiorLayout.setVerticalGroup(
            panelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneldatos, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneletiquetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(etiquetaspaquetepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paquetepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelprincipal.add(panelsuperior, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelprincipal, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Guardar cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem11.setText("Eliminar cliente");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Reportes");

        jMenu4.setText("Clientes");

        jMenuItem2.setText("Por ID");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Por monto");
        jMenu4.add(jMenuItem3);

        jMenu3.add(jMenu4);

        jMenu5.setText("Reservaciones");

        jMenuItem5.setText("Por cliente y fecha");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Cancelados");
        jMenu5.add(jMenuItem6);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Por costo");
        jMenu5.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Por clientes");
        jMenu5.add(jCheckBoxMenuItem2);

        jMenu3.add(jMenu5);

        jMenuItem7.setText("Negocios");
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Carga");
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Bitácora");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ayuda");

        jMenuItem4.setText("Acerca de...");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anualbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anualbuttonActionPerformed
        anualbutton.setSelected(true);
    }//GEN-LAST:event_anualbuttonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (buscartext.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un ID para buscar primero");
        } else {
            try {
                cliente = new Cliente();
                cliente.setCodigo(Integer.parseInt(buscartext.getText()));
                cliente.setNombre(nombretext.getText());
                cliente.setApellido(apellidotext.getText());
                cliente.setCodigoTarjeta(Integer.parseInt(tarjetatext.getText()));
                cliente.setFechaNacimiento(nacimientotext.getText());
                cliente.setTelefono(Integer.parseInt(telefonotext.getText()));
                cliente.setMovil(Integer.parseInt(moviltext.getText()));
                cliente.setClasificacionFrecuencia("Anual");
                clientes.add(cliente);
                log.info("cliente " + cliente.getCodigo() +  " Creado");
            } catch (NumberFormatException e) {
                log.error(e);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        log.info("CARGA MASIVA");
        leerArchivos("01 AerolineasBuses.csv");
        leerArchivos("02 HotelesResorts.csv");
        leerArchivos("03 Cruceros.csv");
        leerArchivos("04 EntidadFinanciera.csv");
        leerArchivos("05 Clientes.csv");
        leerArchivos("06 DestinosTuristicos.csv");
        leerArchivos("07 LugaresE&E.csv");
        leerArchivos("08 Paquetes.csv");
        leerArchivos("09 Reservaciones.csv");
        leerArchivos("10 RentaAutos.csv");
        leerArchivos("11 Asientos.csv");
        leerArchivos("12 Habitaciones.csv");
        leerArchivos("13 Camarotes.csv");  
        log.info("ARCHIVOS CARGADOS A LISTAS");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbuttonActionPerformed
        // TODO add your handling code here:
        if (clientes.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay clientes");
        } else {
            for (int i = 0; i < clientes.size(); i++) {
                if (clientes.get(i).getCodigo() == Integer.parseInt(buscartext.getText())) {
                    nombretext.setText(clientes.get(i).getNombre());
                    apellidotext.setText(clientes.get(i).getApellido());
                    tarjetatext.setText(String.valueOf(clientes.get(i).getCodigoTarjeta()));
                    nacimientotext.setText(clientes.get(i).getFechaNacimiento());
                    telefonotext.setText(String.valueOf(clientes.get(i).getTelefono()));
                    moviltext.setText(String.valueOf(clientes.get(i).getMovil()));
                    i = clientes.size();
                } else if (i == clientes.size() - 1 && Integer.parseInt(buscartext.getText()) != clientes.get(i).getCodigo()) {
                    JOptionPane.showMessageDialog(null, "Tal usuario no existe, registralo como nuevo por favor.");
                }
            }
        }
    }//GEN-LAST:event_buscarbuttonActionPerformed

    private Cliente buscarCliente(int index) {
        Cliente aux = new Cliente();
        for (int i = 0; i < clientes.size(); i++) {
            if (clientes.get(i).getCodigo() == index) {
                aux = clientes.get(i);
            }
        }
        return aux;
    }
    private void lujoradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lujoradiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lujoradiobuttonActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        abrir("logs/Agencia de viajes.log");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int i,j;
        String[] datos = new String[clientes.size()];
        ArrayList<Cliente> auxiliar = new ArrayList<>();
        auxiliar = clientes;
        log.info("Preparando datos a reportar");
        for (i = 0; i < auxiliar.size() - 1; i++) {
            for (j = 0; j < auxiliar.size() - i - 1; j++) {
                if (auxiliar.get(j + 1).getCodigo() < auxiliar.get(j).getCodigo()) {
                    Cliente aux2 = auxiliar.get(j + 1);
                    auxiliar.set(j + 1, auxiliar.get(j));
                    auxiliar.set(j, aux2);
                }
            }
        }
        for(i=0;i<clientes.size();i++){
            datos[i] = String.valueOf(auxiliar.get(i).getCodigo()) + ", "+auxiliar.get(i).getNombre() + ", " + auxiliar.get(i).getApellido();
            log.info("preparando dato " + i);
        }
        crearPagina("Cliente por ID.html",datos);
        abrir("Cliente por ID.html");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        if (clientes.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay clientes");
        } else {
            for (int i = 0; i < clientes.size(); i++) {
                if (clientes.get(i).getCodigo() == Integer.parseInt(buscartext.getText())) {
                    clientes.remove(i);
                } else if (i == clientes.size() - 1 && Integer.parseInt(buscartext.getText()) != clientes.get(i).getCodigo()) {
                    JOptionPane.showMessageDialog(null, "Tal usuario no existe, registralo como nuevo por favor.");
                }
            }
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param A
     * @return A
     */
    public int[] ordenar(int[] A) {
        int i, j, aux;
        for (i = 0; i < A.length - 1; i++) {
            for (j = 0; j < A.length - i - 1; j++) {
                if (A[j + 1] < A[j]) {
                    aux = A[j + 1];
                    A[j + 1] = A[j];
                    A[j] = aux;
                }
            }
        }
        return A;
    }
    
    private void abrir(String fileLocal) {
        try {
            File path = new File(fileLocal);
            Desktop.getDesktop().open(path);
            log.info("Abriendo " + fileLocal);
        } catch (IllegalArgumentException e) {
            log.error(e);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(Level.SEVERE, null, ex);
            log.error(ex);
        }
    }

    private void initRadioButtons(){
        buttonGroup1.add(anualbutton);
        buttonGroup1.add(mensualbutton);
        buttonGroup1.add(regularbutton);
        buttonGroup1.add(frecuentebutton);
        
        buttonGroup2.add(basicobutton);
        buttonGroup2.add(premiumbutton);
        buttonGroup2.add(platinobutton);
        
        buttonGroup3.add(busradiobutton);
        buttonGroup3.add(cruceroradiobutton);
        
        buttonGroup4.add(economicoradiobutton);
        buttonGroup4.add(lujoradiobutton);
    }

    private void leerArchivos(String archivo) {
        String[] datos;
        File f = new File(archivo);
        log.info("Cargando ["+archivo+"]");
        BufferedReader entrada;
        try {
            entrada = new BufferedReader(new FileReader(f));
            String linea;
            while (entrada.ready()) {
                linea = entrada.readLine();
                datos = linea.split(",");
                switch (archivo) {
                    case "01 AerolineasBuses.csv":
                        bus = new AerolineaOBus();
                        bus.setCodigo(Integer.parseInt(datos[0]));
                        bus.setHorarioLlegada(datos[1]);
                        bus.setHorarioSalida(datos[2]);
                        bus.setCapacidad(Integer.parseInt(datos[3]));
                        bus.setCodigoDestino(Integer.parseInt(datos[4]));
                        buses.add(bus);
                        log.info(datos[0] + " añadido");
                        break;
                    case "02 HotelesResorts.csv":
                        hotel = new HotelOResort();
                        hotel.setCodigo(Integer.parseInt(datos[0]));
                        hotel.setDireccion(datos[1]);
                        hotel.setNoCuartos(Integer.parseInt(datos[2]));
                        hotel.setCodigoDestino(Integer.parseInt(datos[3]));
                        hoteles.add(hotel);
                        log.info(datos[0] + " añadido");
                        break;
                    case "03 Cruceros.csv":
                        crucero = new Crucero();
                        crucero.setCodigo(Integer.parseInt(datos[0]));
                        crucero.setFechaSalida(datos[1]);
                        crucero.setFechaLlegada(datos[2]);
                        crucero.setCapacidad(Integer.parseInt(datos[3]));
                        crucero.setDuracion(Integer.parseInt(datos[4]));
                        crucero.setDescripcion(datos[5]);
                        cruceros.add(crucero);
                        log.info(datos[0] + " añadido");
                        break;
                    case "04 EntidadFinanciera.csv":
                        financiera = new EntidadFinanciera();
                        financiera.setCodigo(Integer.parseInt(datos[0]));
                        financiera.setCodigoCliente(Integer.parseInt(datos[1]));
                        financiera.setTipoTarjeta(datos[2]);
                        financiera.setCodigoTarjeta(Integer.parseInt(datos[3]));
                        financiera.setSaldo(Integer.parseInt(datos[4]));
                        financiera.setLimite(Integer.parseInt(datos[5]));
                        financieras.add(financiera);
                        log.info(datos[0] + " añadido");
                        break;
                    case "05 Clientes.csv":
                        cliente = new Cliente();
                        cliente.setCodigo(Integer.parseInt(datos[0]));
                        cliente.setNombre(datos[1]);
                        cliente.setApellido(datos[2]);
                        cliente.setCodigoTarjeta(Integer.parseInt(datos[3]));
                        cliente.setFechaNacimiento(datos[4]);
                        cliente.setTelefono(Integer.parseInt(datos[5]));
                        cliente.setMovil(Integer.parseInt(datos[6]));
                        cliente.setDireccionHabitacion(datos[7]);
                        cliente.setClasificacionFrecuencia(datos[8]);
                        cliente.setClasificacionMonoto(datos[9]);
                        clientes.add(cliente);
                        log.info(datos[0] + " añadido");
                        break;
                    case "06 DestinosTuristicos.csv":
                        turistico = new Turistico();
                        turistico.setCodigo(Integer.parseInt(datos[0]));
                        turistico.setPais(datos[1]);
                        turistico.setCiudad(datos[2]);
                        turistico.setDireccion(datos[3]);
                        turistico.setDescripcion(datos[4]);
                        turistico.setDescripcionSeguridad(datos[5]);
                        turisticos.add(turistico);
                        log.info(datos[0] + " añadido");
                        break;
                    case "07 LugaresE&E.csv":
                        entretenimiento = new Entretenimiento();
                        entretenimiento.setCodigo(Integer.parseInt(datos[0]));
                        entretenimiento.setNombre(datos[1]);
                        entretenimiento.setDescripcion(datos[2]);
                        entretenimiento.setPais(datos[3]);
                        entretenimiento.setCiudad(datos[4]);
                        entretenimiento.setDireccion(datos[5]);
                        entretenimiento.setMinEdad(Integer.parseInt(datos[6]));
                        entretenimiento.setHorarioActividad(datos[7]);
                        entretenimiento.setHorarioFuncion(datos[8]);
                        entretenimiento.setRecomendacionSeguridad(datos[9]);
                        entretenimiento.setCodigoDestino(PROPERTIES);
                        entretenimientos.add(entretenimiento);
                        log.info(datos[0] + " añadido");
                        break;
                    case "08 Paquetes.csv":
                        paquete = new Paquete();
                        paquete.setCodigo(Integer.parseInt(datos[0]));
                        paquete.setTipo(datos[1]);
                        paquete.setClase(datos[2]);
                        paquete.setNoViajeros(Integer.parseInt(datos[3]));
                        paquete.setCodigoTransporte(Integer.parseInt(datos[4]));
                        paquete.setCodigoHospedaje(Integer.parseInt(datos[5]));
                        paquete.setCodigoCrucero(Integer.parseInt(datos[6]));
                        paquete.setCodigoRentaAuto(Integer.parseInt(datos[7]));
                        paquete.setCodigoLugarTuristico(Integer.parseInt(datos[8]));
                        paquete.setCodigoLugarEntretenimiento(Integer.parseInt(datos[9]));
                        paquete.setCosto(Integer.parseInt(datos[10]));
                        paquetes.add(paquete);
                        log.info(datos[0] + " añadido");
                        break;
                    case "09 Reservaciones.csv":
                        reservacion = new Reservacion();
                        reservacion.setCodigo(Integer.parseInt(datos[0]));
                        reservacion.setCodigoPaquete(Integer.parseInt(datos[1]));
                        reservacion.setCodigoCliente(Integer.parseInt(datos[2]));
                        reservacion.setFechaReservacion(datos[3]);
                        reservacion.setFechaSalida(datos[4]);
                        reservacion.setDuracionViaje(Integer.parseInt(datos[5]));
                        reservacion.setEstado(datos[6]);
                        reservacion.setSaldoPendiente(Integer.parseInt(datos[7]));
                        reservaciones.add(buses);
                        log.info(datos[0] + " añadido");
                        break;
                    case "10 RentaAutos.csv":
                        auto = new RentaAuto();
                        auto.setCodigo(Integer.parseInt(datos[0]));
                        auto.setCodigoCliente(Integer.parseInt(datos[1]));
                        auto.setNoPasajeros(Integer.parseInt(datos[2]));
                        auto.setTipoTerreno(datos[3]);
                        auto.setDuracion(Integer.parseInt(datos[4]));
                        auto.setMonto(Integer.parseInt(datos[5]));
                        auto.setFechaEntrega(datos[6]);
                        auto.setFechaDevolucion(datos[7]);
                        auto.setCondiciones(datos[8]);
                        autos.add(auto);
                        log.info(datos[0] + " añadido");
                        break;
                    case "11 Asientos.csv":
                        asiento = new Asiento();
                        asiento.setCodigoTransporte(Integer.parseInt(datos[0]));
                        asiento.setCodigoReservacion(Integer.parseInt(datos[1]));
                        asiento.setNoAsientoViajero(Integer.parseInt(datos[2]));
                        asiento.setClase(datos[3]);
                        asiento.setCosto(Integer.parseInt(datos[4]));
                        asientos.add(asiento);
                        log.info(datos[0] + " añadido");
                        break;
                    case "12 Habitaciones.csv":
                        habitacion = new Habitacion();
                        habitacion.setCodigoHotelOResort(Integer.parseInt(datos[0]));
                        habitacion.setNoHabitacion(Integer.parseInt(datos[1]));
                        habitacion.setCodigoReservacion(Integer.parseInt(datos[2]));
                        habitacion.setNoPersonas(Integer.parseInt(datos[3]));
                        habitacion.setCosto(Integer.parseInt(datos[4]));
                        habitacion.setClase(datos[5]);
                        habitaciones.add(habitacion);
                        log.info(datos[0] + " añadido");
                        break;
                    case "13 Camarotes.csv":
                        camarote = new Camarote();
                        camarote.setCodigoCrucero(Integer.parseInt(datos[0]));
                        camarote.setCodigoReservacion(Integer.parseInt(datos[1]));
                        camarote.setNoHabitacion(Integer.parseInt(datos[2]));
                        camarote.setCosto(Integer.parseInt(datos[3]));
                        camarotes.add(camarote);
                        log.info(datos[0] + " añadido");
                        break;
                }
            }
        } catch (IOException | NumberFormatException e) {
            log.error(e);
        }
    }
    
    private void crearPagina(String localFile, String[] lista) {
        FileWriter filewriter = null;
        PrintWriter printw = null;
        int i;
        try {
            filewriter = new FileWriter(localFile);
            printw = new PrintWriter(filewriter);
            printw.println("<html>");
            printw.println("<head><title>" + localFile + "</title></head>");
            printw.println("<body bgcolor=\"#99CC99\">");
            for (i = 0; i < lista.length; i++) {
                printw.println("<center><h1><font color=\"navy\">" + lista[i] + "</font></h1></center>");
                log.info(localFile + "Imprimiento dato " + i);
            }
            printw.println("</body>");
            printw.println("</html>");
            printw.close();
            log.info("Reporte " +localFile + " finalizado");
        } catch (FileNotFoundException e) {
            log.error(e);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(Level.SEVERE, null, ex);
            log.error(ex);
        }
    }
            
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton anualbutton;
    private javax.swing.JTextField apellidotext;
    private javax.swing.JRadioButton basicobutton;
    private javax.swing.JButton buscarbutton;
    private javax.swing.JTextField buscartext;
    private javax.swing.JRadioButton busradiobutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton cruceroradiobutton;
    private javax.swing.JRadioButton economicoradiobutton;
    private javax.swing.JPanel etiquetaspaquetepanel;
    private javax.swing.JRadioButton frecuentebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton lujoradiobutton;
    private javax.swing.JRadioButton mensualbutton;
    private javax.swing.JTextField moviltext;
    private javax.swing.JTextField nacimientotext;
    private javax.swing.JTextField nombretext;
    private javax.swing.JPanel panelbuscar;
    private javax.swing.JPanel paneldatos;
    private javax.swing.JPanel paneletiquetas;
    private javax.swing.JPanel panelinferior;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JPanel panelradiobuttons;
    private javax.swing.JPanel panelsuperior;
    private javax.swing.JPanel paquetepanel;
    private javax.swing.JRadioButton platinobutton;
    private javax.swing.JRadioButton premiumbutton;
    private javax.swing.JRadioButton regularbutton;
    private javax.swing.JTextField tarjetatext;
    private javax.swing.JTextField telefonotext;
    // End of variables declaration//GEN-END:variables
}
